apiVersion: v1
kind: Template
metadata:
  name: network-infra-named
parameters:
- name: APP_NAME
  value: named-master
- name: BASE_IMAGESTREAM_NAME
  value: network-base-image
- name: BASE_IMAGE_STREAM_TAG
  value: latest
- name: ACL_LOCAL_NETS
  value: "172.16.10.0/24 172.17.0.0/16 172.18.0.0/16"
- name: MASTER_LOCAL_ZONE_NAME
  value: ds.test
- name: LOCAL_ZONE_FORWARD_NET
  value: "172.17.7"
- name: MASTER_SERVERS
  description: IP address of Master Named Service (Service name of master service, ip address)
  value: ""
- name: CPU_REQUEST
  value: 100m
- name: CPU_LIMIT
  value: 300m
- name: MEMORY_REQUEST
  value: 64Mi
- name: MEMORY_LIMIT
  value: 128Mi
#- name: BASE_IMAGE_NAMESPACE
#  value: network-infra
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: ImageStreamTag
        name: ${APP_NAME}
      name: latest
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    source:
      contextDir: dockerfiles/named
      git:
        uri: https://github.com/dsevost/network-infra
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: ${BASE_IMAGESTREAM_NAME}:${BASE_IMAGE_STREAM_TAG}
#          namespace: ${BASE_IMAGE_STREAM_NAMESPACE}
      type: Docker
    triggers:
    - type: ConfigChange
    - github:
        secret: 0SyIow9GF6GCRzAIOp0o
      type: GitHub
    - generic:
        secret: zmsi-CKr5cOsODkWi-ZD
      type: Generic
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
      spec:
        containers:
        - env:
          - name: MASTER_LOCAL_ZONE_NAME
            value: ${MASTER_LOCAL_ZONE_NAME}
          - name: MASTER_SERVERS
            value: ${MASTER_SERVERS}
          image: " "
          name: ${APP_NAME}
          livenessProbe:
            initialDelaySeconds: 10
            tcpSocket:
              port: 8053
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
              - /usr/local/bin/readyness.sh
            initialDelaySeconds: 10
            timeoutSeconds: 10
          ports:
          - containerPort: 8053
            protocol: TCP
          - containerPort: 8053
            protocol: UDP
          volumeMounts:
          - mountPath: /etc/named
            name: named-etc
          - mountPath: /var/named
            name: named-data
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
        dnsPolicy: ClusterFirst
        initContainers:
        - env:
          - name: ACL_LOCAL_NETS
            value: ${ACL_LOCAL_NETS}
          - name: MASTER_LOCAL_ZONE_NAME
            value: ${MASTER_LOCAL_ZONE_NAME}
          - name: LOCAL_ZONE_FORWARD_NET
            value: ${LOCAL_ZONE_FORWARD_NET}
          command:
          - /usr/local/bin/init-named.sh
          image: " "
          name: init-named
          volumeMounts:
          - mountPath: /etc/named
            name: named-etc
          - mountPath: /var/named
            name: named-data
        volumes:
        - emptyDir: {}
          name: named-etc
        - emptyDir: {}
          name: named-data
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}
        - init-named
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}-ingress
  spec:
    externalTrafficPolicy: Cluster
    ports:
    - port: 53
      protocol: UDP
      targetPort: 8053
    selector:
      deploymentconfig: ${APP_NAME}
    sessionAffinity: None
    type: LoadBalancer
